import type {
  ConnectionMotion,
  ConnectionStyle,
  InteractionMotion,
  NodeMotion,
  NodeStyle,
  PortStyle,
  Theme,
} from "../editor/types.ts";

export const darkTheme: Readonly<Theme> = Object.freeze({
  canvas: "#16191f",
  surface: "#20242c",
  node: "#282e38",
  input: "#20252e",
  border: "#465160",
  text: "#edf1f7",
  muted: "#a6b0c0",
  accent: "#a9a1ff",
  grid: "#303743",
  danger: "#ff8f97",
  success: "#6dde93",
  font:
    'Inter, ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  portColors: Object.freeze({
    any: "#a6b0c0",
    number: "#83bdff",
    string: "#dcabf6",
    boolean: "#efc574",
    records: "#70aef9",
    event: "#e9ad70",
    object: "#70aef9",
  }),
});
export const glassNodeStyle: Readonly<NodeStyle> = Object.freeze({
  radius: 24,
  padding: 16,
  headerHeight: 52,
  footerHeight: 28,
  controlRadius: 12,
  controlHeight: 32,
  controlGap: 6,
  labelHeight: 22,
  inputPadding: 10,
  inputPaddingY: 7,
  inputColumnWidth: 72,
  titleSize: 15,
  titleWeight: 600,
  fontSize: 13,
  labelSize: 12,
  lineHeight: 18,
  iconSize: 30,
  iconRadius: 10,
  borderWidth: 1,
  selectionWidth: 1.5,
  opacity: 0.48,
  blur: 0,
  refraction: 10,
  refractionWidth: 16,
  highlight: "#ffffff",
  highlightOpacity: 0.72,
  tintOpacity: 0,
  lightOpacity: 0.14,
  shadow: "rgba(0, 0, 0, 0.36)",
  shadowBlur: 24,
  shadowOffset: 8,
  dragShadow: 16,
  glow: 0,
  dividerOpacity: 0.18,
  disabledOpacity: 0.45,
});

/** A complete effect override, useful for flat or opaque themes. */
export const flatNodeStyle: Readonly<Partial<NodeStyle>> = Object.freeze({
  radius: 6,
  opacity: 1,
  blur: 0,
  refraction: 0,
  refractionWidth: 0,
  highlightOpacity: 0,
  tintOpacity: 0,
  lightOpacity: 0,
  shadowBlur: 0,
  shadowOffset: 0,
  dragShadow: 0,
  glow: 0,
});

export const defaultNodeMotion: Readonly<NodeMotion> = Object.freeze({
  duration: 180,
  easing: (t: number) => 1 - (1 - t) ** 3,
  runningPeriod: 1200,
});

export const defaultPortMotion: Readonly<InteractionMotion> = Object.freeze({
  duration: 160,
  easing: (t: number) => 1 - (1 - t) ** 3,
});
export const defaultConnectionMotion: Readonly<ConnectionMotion> = Object
  .freeze({ ...defaultPortMotion, duration: 180, flowSpeed: 100 });
export const defaultPortStyle: Readonly<PortStyle> = Object.freeze({
  radius: 5,
  width: 1.5,
  coreRadius: null,
  indicatorWidth: 1.5,
  hitRadius: 10,
  hoverScale: 1.15,
  haloWidth: 2,
  haloOpacity: 0.2,
  color: null,
  fill: null,
  activeColor: null,
  invalidColor: null,
  opacity: 1,
  incompatibleOpacity: 0.35,
  labelColor: null,
  labelSize: 12,
  labelGap: 9,
  labelOffset: 18,
  labelWidth: 110,
});
export const defaultConnectionStyle: Readonly<ConnectionStyle> = Object.freeze({
  color: null,
  targetColor: null,
  activeColor: null,
  invalidColor: null,
  width: 2.25,
  hoverWidth: 3,
  selectedWidth: 3.25,
  hitWidth: 12,
  opacity: 0.85,
  outlineWidth: 0,
  outlineColor: null,
  outlineOpacity: 0.65,
  dash: Object.freeze([]),
  pendingDash: Object.freeze([5, 7]),
  pendingOpacity: 0.7,
  flowWidth: 1.8,
  flowLength: 22,
  flowSpacing: 150,
  flowColor: null,
  labelSize: 12,
  labelColor: null,
  labelBackground: null,
  labelPadding: 6,
  labelRadius: 6,
  labelOffset: 12,
});

export const touchNodeStyle: Readonly<Partial<NodeStyle>> = Object.freeze({
  headerHeight: 56,
  controlHeight: 42,
  fontSize: 16,
  labelSize: 15,
  lineHeight: 22,
});
