import type { EditorPreset } from "../editor/types.ts";

const still = Object.freeze({ duration: 0, easing: (t: number) => t });
/** Layout and hit testing without any pixels, material, palette, or animation.
 * This entry does not import the default painter or its effects. */
export const unstyledPreset: Readonly<EditorPreset> = Object.freeze({
  theme: Object.freeze({
    canvas: "transparent",
    surface: "transparent",
    node: "transparent",
    input: "transparent",
    border: "transparent",
    text: "transparent",
    muted: "transparent",
    accent: "transparent",
    grid: "transparent",
    danger: "transparent",
    success: "transparent",
    font: "system-ui",
    portColors: Object.freeze({ any: "transparent" }),
  }),
  nodes: Object.freeze({
    style: Object.freeze({
      radius: 0,
      padding: 16,
      headerHeight: 52,
      footerHeight: 0,
      controlRadius: 0,
      controlHeight: 32,
      controlGap: 6,
      labelHeight: 22,
      inputPadding: 10,
      inputPaddingY: 7,
      inputColumnWidth: 72,
      titleSize: 15,
      titleWeight: 400,
      fontSize: 13,
      labelSize: 12,
      lineHeight: 18,
      iconSize: 0,
      iconRadius: 0,
      borderWidth: 0,
      selectionWidth: 0,
      opacity: 1,
      blur: 0,
      refraction: 0,
      refractionWidth: 0,
      highlight: "transparent",
      highlightOpacity: 0,
      tintOpacity: 0,
      lightOpacity: 0,
      shadow: "transparent",
      shadowBlur: 0,
      shadowOffset: 0,
      dragShadow: 0,
      glow: 0,
      dividerOpacity: 0,
      disabledOpacity: 1,
    }),
    motion: Object.freeze({ ...still, runningPeriod: 0 }),
  }),
  ports: Object.freeze({
    style: Object.freeze({
      radius: 5,
      width: 0,
      coreRadius: null,
      indicatorWidth: 0,
      hitRadius: 10,
      hoverScale: 1,
      haloWidth: 0,
      haloOpacity: 0,
      color: null,
      fill: null,
      activeColor: null,
      invalidColor: null,
      opacity: 1,
      incompatibleOpacity: 1,
      labelColor: null,
      labelSize: 12,
      labelGap: 9,
      labelOffset: 18,
      labelWidth: 110,
    }),
    motion: still,
  }),
  connections: Object.freeze({
    style: Object.freeze({
      color: null,
      targetColor: null,
      activeColor: null,
      invalidColor: null,
      width: 0,
      hoverWidth: 0,
      selectedWidth: 0,
      hitWidth: 12,
      opacity: 1,
      outlineWidth: 0,
      outlineColor: null,
      outlineOpacity: 0,
      dash: Object.freeze([]),
      pendingDash: Object.freeze([]),
      pendingOpacity: 1,
      flowWidth: 0,
      flowLength: 0,
      flowSpacing: 0,
      flowColor: null,
      labelSize: 12,
      labelColor: null,
      labelBackground: null,
      labelPadding: 0,
      labelRadius: 0,
      labelOffset: 0,
    }),
    motion: Object.freeze({ ...still, flowSpeed: 0 }),
  }),
  menu: Object.freeze({ rowHeight: 34, touchRowHeight: 44 }),
  createPainter: () => ({}),
});
