name: Publish package to NPM

on:
  release:
    types: [published]

jobs:
  test:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.9.7
      - run: deno install --frozen
      - run: deno task check

  publish-npm:
    needs: test
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/jod
          registry-url: https://registry.npmjs.org/
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.9.7
      - run: deno install --frozen
      - run: deno task build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
